In [1]:
import numpy as np

In [4]:
A1=np.array([1,2,3,4]) # create 1D array
print(A1)

[1 2 3 4]


In [3]:
A2=np.array([[1,2,3,4],[5,6,7,8]]) # create 1D array
A2[0,1]

2

In [ ]:
A3=np.array(['a','b','c'])
A3[1]

'b'

In [ ]:
A4=np.array(['a1','b2','c3','d44'])
A4[1][0]

'b'

In [ ]:
print(A1.size) #how many items present in a array
print(A2.size)
print(A1.shape) #number od rows and cols
print(A2.shape)


4
8
(4,)
(2, 4)


In [ ]:
type(A1) # give the type of data present in one_d_array variable

numpy.ndarray

In [ ]:
#Create NumPy 1D array using arange() function
arr1 = np.arange(1,10)
print(arr1)
arr2 = np.arange(1,10,2)
print(arr2)


[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
#Convert 1D array to multidimensional array using reshape() function
arr_new=np.reshape(arr1, (3,3))
print(arr_new)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
oarr=arr_new.flatten()
print(oarr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
ones_array = np.ones((3, 4))
print("Ones Array:")
print(ones_array)
print()

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



In [ ]:
mark1, mark2, mark3 = np.loadtxt('Mark.txt',
                    skiprows=1,
                    unpack=True)
Mark_Array=np.array([mark1,mark2,mark3])
print(Mark_Array)

[[60. 99. 55. 84. 55. 77. 80. 90.]
 [66. 78. 61. 81. 54. 72. 80. 95.]
 [70. 88. 54. 73. 53. 79. 80. 93.]]


In [ ]:
Mark_Array=Mark_Array.T

In [ ]:
import pandas as pd
import numpy as np
DF1=pd.DataFrame([1,2,3])
print(DF1)

   0
0  1
1  2
2  3


In [ ]:
DF2=pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))
print(DF2)
print(DF2.shape)
print(len(DF2))

   0  1  2
0  1  2  3
1  4  5  6
(2, 3)
2


In [ ]:
df = pd.DataFrame({"A":[1,4,7], "B":[2,5,8], "C":[3,6,9]})
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [ ]:
# Using `iloc[]`
print(df.iloc[0][0])

# Using `loc[]`
print(df.loc[0]['A'])

# Using `at[]`
print(df.at[0,'A'])

# Using `iat[]`
print(df.iat[0,0])

1
1
1
1


<ipython-input-52-af61aad72afb>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[0][0])


In [ ]:
new_row = pd.DataFrame([[1, 4, 7]], columns=df.columns)
df = pd.concat([df, new_row], ignore_index=True) # Call pd.concat, assign result back to df
print(df) # Print the updated DataFrame to see the changes

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
3  1  4  7
